// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-HqH-I_NfHjZ3YUDSspeoKvRmuqCbOCY',
    appId: '1:78288292987:web:a1ac9adf9cc71174d266de',
    messagingSenderId: '78288292987',
    projectId: 'authentication-example-e97ae',
    authDomain: 'authentication-example-e97ae.firebaseapp.com',
    storageBucket: 'authentication-example-e97ae.appspot.com',
    measurementId: 'G-GFZ3PHFHBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsRj9Y2BlZ6F1w42Nwt8wGjeOSXGHP3PQ',
    appId: '1:78288292987:android:7583adf676888eb5d266de',
    messagingSenderId: '78288292987',
    projectId: 'authentication-example-e97ae',
    storageBucket: 'authentication-example-e97ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7YCCE9uf7IVyvcK8USopfvQdZd95nDQ',
    appId: '1:78288292987:ios:06d8d2eba2c7ed9ad266de',
    messagingSenderId: '78288292987',
    projectId: 'authentication-example-e97ae',
    storageBucket: 'authentication-example-e97ae.appspot.com',
    iosClientId: '78288292987-ajki3sjgnk0ccuh3e2i4dmfkqqib8aef.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthenticationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL7YCCE9uf7IVyvcK8USopfvQdZd95nDQ',
    appId: '1:78288292987:ios:06d8d2eba2c7ed9ad266de',
    messagingSenderId: '78288292987',
    projectId: 'authentication-example-e97ae',
    storageBucket: 'authentication-example-e97ae.appspot.com',
    iosClientId: '78288292987-ajki3sjgnk0ccuh3e2i4dmfkqqib8aef.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthenticationExample',
  );
}
